### ISSUE TITLE
Cmd-L no longer works by default

### ISSUE THREAD

**Issue by njx** [mikechambers/StringConvert#1]
Cmd-L is taken by "Go to Line", so it doesn't work as the default for "convert to lower case" in StringConvert.

**Comment by mikechambers** [comment]
Thanks. Ill fix this.

In general, what is the guidance for extension developers for choosing keyboard shortcuts? Do we have a document that lists all of the shortcuts that brackets uses?

**Comment by mikechambers** [comment]
Fixed by removing shortcut.
