### ISSUE TITLE
Unexpected results encoding a URL

### ISSUE THREAD

**Issue by redmunds** [mikechambers/StringConvert#3]
1. I selected this URL "images/special items.jpg"
2. Encode URI Component

Results:
URL was converted to: images%2Fspecial%20items.jpg

Expected Results:
I did not expect forward slash to get converted to %2F.

I guess it does say “component”, so it’s probably behaving as designed, but would anyone really convert each component 1 by 1? Seems like you’d want to convert the whole URL at once (and never want to convert the forward slash)

**Comment by mikechambers** [comment]
This is working as expected:

https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/encodeURIComponent

This is for encoding strings that will be sent as a url parameter.

**Comment by redmunds** [comment]
OK, fair enough. Then I'd like to change this to a Feature Request for "Encode URI" and "Decode URI" commands :)
